// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2BtX3XhR-WeaQLLzn4HzqZqT1kISXAE',
    appId: '1:522217107399:web:5f273904f9a3dcb594b3e2',
    messagingSenderId: '522217107399',
    projectId: 'flocksense-app',
    authDomain: 'flocksense-app.firebaseapp.com',
    storageBucket: 'flocksense-app.firebasestorage.app',
    measurementId: 'G-14W4P0LG77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkllx22TkV5JVuDeZVCwEK4CG0WBUguMI',
    appId: '1:522217107399:android:fbcb7e50007d28a094b3e2',
    messagingSenderId: '522217107399',
    projectId: 'flocksense-app',
    storageBucket: 'flocksense-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPm9kO1zdF13kKhb2PkZDmvQij_xq9m2Q',
    appId: '1:522217107399:ios:f9a22ad2ba7a852d94b3e2',
    messagingSenderId: '522217107399',
    projectId: 'flocksense-app',
    storageBucket: 'flocksense-app.firebasestorage.app',
    androidClientId:
        '522217107399-g6ul8tfsr3o9g6jfu677n6jsv90vqg8k.apps.googleusercontent.com',
    iosClientId:
        '522217107399-683kvdbcnpc2gv760eav2h4j1o317rrp.apps.googleusercontent.com',
    iosBundleId: 'com.flocksense.app.flockSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPm9kO1zdF13kKhb2PkZDmvQij_xq9m2Q',
    appId: '1:522217107399:ios:f9a22ad2ba7a852d94b3e2',
    messagingSenderId: '522217107399',
    projectId: 'flocksense-app',
    storageBucket: 'flocksense-app.firebasestorage.app',
    androidClientId:
        '522217107399-g6ul8tfsr3o9g6jfu677n6jsv90vqg8k.apps.googleusercontent.com',
    iosClientId:
        '522217107399-683kvdbcnpc2gv760eav2h4j1o317rrp.apps.googleusercontent.com',
    iosBundleId: 'com.flocksense.app.flockSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-2BtX3XhR-WeaQLLzn4HzqZqT1kISXAE',
    appId: '1:522217107399:web:8f24beeb8ef780e394b3e2',
    messagingSenderId: '522217107399',
    projectId: 'flocksense-app',
    authDomain: 'flocksense-app.firebaseapp.com',
    storageBucket: 'flocksense-app.firebasestorage.app',
    measurementId: 'G-ZG82ZCL033',
  );
}
