name: flock_sense
description: "FlockSense poultry farm management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.2

  # Authentication
  google_sign_in: ^6.2.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Charts
  fl_chart: ^0.69.2

  # Utilities
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true